global with sharing class SampleJobFinishCallback {
       //wuhuuuu
       global void execute(Account job, String status) {
           String mergeResolution;
           Boolean conflict2;
           System.debug('hello');
           System.debug('heellooo');
           // Start execution of next job template
           // The callback context is Automated process user
           System.debug('yolo');
           String hello;
           Boolean conflict = false;
       }
       Integer helloWorld;
   }
