global with sharing class SampleJobFinishCallback {
       //wuhuuuu
       global void execute(Account job, String status) {
           String {!Environment.{!Environment.tester}ter}t;
           Boolean {!Environment.{!Environment.tester}ter}ssst22;
           System.debug('hello');
           System.debug('heellooo');
           // Start execution of next job template
           // The callback context is Automated process user
           System.debug('yolo');
           String hello;
           Integer conflict = 0;
       }
       Integer helloWorld;
   }